
server:
  port: 19888
  max-http-header-size: 81920

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 15MB
      max-request-size: 15MB

  datasource:
    url: jdbc:mysql://101.43.139.84:3306/test4
    username: zcy
    password: zcy2013.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource   #数据源类型，使用Druid
    tomcat:
      max-active: 5
      max-wait: 2000
      max-idle: 0
      min-idle: 0
      initial-size: 0
      test-on-borrow: true
      validation-query: "SELECT 1 FROM DUAL"
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: zcy2013.
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ht.api.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true


sa-token:
  # jwt秘钥
  jwt-secret-key: Ultra@529826
  # token 名称（同时也是 cookie 名称）
  token-name: zcyyjq
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

logging:
  level:
    root: error
    org.springframework: error
    com.ht.api: debug
    #org.springframework.boot.autoconfigure: DEBUG
    #org.springframework.web.cors: DEBUG